language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    services:
    - docker
    before_install:
    - docker run -d --name xenial -v $(dirname $(pwd)):/root -v /home/travis/package:/package
      -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS_TAG="$TRAVIS_TAG" -w /root nimmis/ubuntu:16.04
    - docker exec -it xenial /root/obs-websocket/CI/install-dependencies-xenial.sh
    script:
    - docker exec -it xenial /root/obs-websocket/CI/build-xenial.sh
    after_success:
    - docker exec -it xenial /root/obs-websocket/CI/package-xenial.sh

