pool:
  vmImage: 'macOS-10.13'

steps:
- script: ./CI/install-dependencies-osx.sh
  displayName: 'Install Dependencies'

- script: ./CI/before-script-osx.sh
  displayName: 'CMake'

- bash: |
     cd ./build
     make -j4
     cd -
  displayName: 'Build'
